using UdonSharp;
using UnityEngine;
using VRC.SDK3.StringLoading;
using VRC.SDK3.Persistence;
using VRC.SDKBase;
using VRC.Udon.Common.Interfaces;

namespace StudioPeipeiko.VRClarity.Runtime
{
    [UdonBehaviourSyncMode(BehaviourSyncMode.None)]
    public class VRClarityTracker : UdonSharpBehaviour
    {
        // ===== Inspector Settings =====
        [Header("VRClarity Settings")]
        [Tooltip("API Key ID (sk_ + 24 hex characters)")]
        public string keyId = "";

        [Tooltip("Encryption Key (hex 64 characters)")]
        public string encryptionKey = "";

        [Tooltip("Check this just before uploading the published world. While unchecked, NO heartbeats are sent (local-debug protection); only a configuration-check request is made.")]
        public bool enableTracking = false;

        // ===== Pre-baked URL Pools (Auto-generated by Editor) =====
        [HideInInspector] public VRCUrl[] _stayUrls = new VRCUrl[0];  // 9 URLs
        [HideInInspector] public VRCUrl[] _moveUrls = new VRCUrl[0];  // 6 URLs
        [HideInInspector] public VRCUrl[] _visitUrls = new VRCUrl[0]; // 20 URLs
        [HideInInspector] public VRCUrl[] _platformUrls = new VRCUrl[0]; // 5 URLs
        [HideInInspector] public VRCUrl[] _pcUrls = new VRCUrl[0];    // 81 URLs (0-80)
        [HideInInspector] public VRCUrl _verifyUrl;                   // 1 URL (config check)

        // ===== Constants =====
        private const int QUEUE_SIZE = 32;
        private const float SEND_INTERVAL = 5.0f;
        private const float DISTANCE_SAMPLE_INTERVAL = 5.0f;
        private const float PC_SEND_INTERVAL = 300.0f;
        private const string PERSISTENCE_KEY = "vrclarity_vc";

        // ===== Stay Milestones (seconds) =====
        private float[] _stayThresholds;

        // ===== Move Milestones (meters) =====
        private float[] _moveThresholds;

        // ===== Visit Buckets =====
        private int[] _visitBuckets;

        // ===== Send Queue (Ring Buffer) =====
        private VRCUrl[] _sendQueueUrls;
        private int _sendQueueHead = 0;
        private int _sendQueueTail = 0;

        // ===== Tracking State =====
        private float _joinTime = 0f;
        private Vector3 _lastPosition = Vector3.zero;
        private float _lastDistanceSampleTime = 0f;
        private float _accumulatedDistance = 0f;
        private float _lastPcSendTime = 0f;
        private float _lastRequestTime = -SEND_INTERVAL; // Allow immediate first send

        // ===== Milestone Sent Flags =====
        private bool[] _sentStay;
        private bool[] _sentMove;

        // ===== Initialization Flags =====
        private bool _initialized = false;
        private bool _visitSent = false;

        // ===== Tracking Gate =====
        // Heartbeats are sent only in a real (non-editor) build with tracking
        // explicitly enabled. Otherwise (editor play/ClientSim, or a build with
        // enableTracking unchecked) we send only the config-check URL once, which
        // the backend excludes from the public tracking ledger. This keeps worlds
        // that are merely tested locally off the ledger.
        private bool _trackingActive = false;
        private bool _verifySent = false;

        private void Start()
        {
            _stayThresholds = new float[] { 60f, 300f, 900f, 1800f, 3600f, 7200f, 14400f, 21600f, 28800f };
            _moveThresholds = new float[] { 10f, 50f, 150f, 400f, 1000f, 2500f };
            _visitBuckets = new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 25, 30, 40, 50, 75, 100, 150, 200 };
            _sentStay = new bool[_stayThresholds.Length];
            _sentMove = new bool[_moveThresholds.Length];
            _sendQueueUrls = new VRCUrl[QUEUE_SIZE];

            if (_stayUrls == null || _stayUrls.Length == 0)
            {
#if UNITY_EDITOR
                Debug.LogWarning("[VRClarity] URL pools are empty. Blueprint ID may not be set in VRC_SceneDescriptor. No URL requests will be sent.");
#else
                Debug.LogWarning("[VRClarity] URL pools are empty. URLs were not baked before build.");
#endif
            }
        }

        public override void OnPlayerJoined(VRCPlayerApi player)
        {
            if (player == null || !player.isLocal) return;
            if (_initialized) return;

            _initialized = true;
            _joinTime = Time.time;
            _lastPosition = player.GetPosition();
            _lastDistanceSampleTime = Time.time;
            _lastPcSendTime = Time.time;

            // Decide once whether real heartbeats may be sent. In the editor we
            // always suppress them; in a real build they require enableTracking.
#if UNITY_EDITOR
            _trackingActive = false;
#else
            _trackingActive = enableTracking;
#endif
            if (!_trackingActive)
            {
                Debug.Log("[VRClarity] Tracking disabled (local debug or enableTracking unchecked). Sending config-check only; no heartbeats.");
            }

            // --- Platform Detection (one-time on join) ---
            SendPlatformEvent(player);

            // --- Initial Player Count ---
            if (_pcUrls != null && _pcUrls.Length > 0)
            {
                int pc = Mathf.Clamp(VRCPlayerApi.GetPlayerCount(), 0, 80);
                EnqueueSend(_pcUrls[pc]);
            }

            Debug.Log("[VRClarity] Tracker initialized. Waiting for PlayerData...");
        }

        public override void OnPlayerRestored(VRCPlayerApi player)
        {
            if (player == null || !player.isLocal) return;

            if (_visitSent) return;
            _visitSent = true;

            // --- Visit Count (read after PlayerData is loaded) ---
            int visitCount = PlayerData.GetInt(player, PERSISTENCE_KEY) + 1;
            PlayerData.SetInt(PERSISTENCE_KEY, visitCount);

            if (_visitUrls != null && _visitUrls.Length > 0)
            {
                int bucketIndex = 0;
                for (int i = _visitBuckets.Length - 1; i >= 0; i--)
                {
                    if (visitCount >= _visitBuckets[i])
                    {
                        bucketIndex = i;
                        break;
                    }
                }
                EnqueueSend(_visitUrls[bucketIndex]);
            }

            Debug.Log($"[VRClarity] Visit count: {visitCount}");
        }

        private void Update()
        {
            if (!_initialized) return;

            VRCPlayerApi localPlayer = Networking.LocalPlayer;
            if (localPlayer == null || !localPlayer.IsValid()) return;

            float now = Time.time;
            float elapsed = now - _joinTime;

            // ===== Stay Time Check =====
            CheckStayMilestones(elapsed);

            // ===== Movement Distance Check (sample every 5 seconds) =====
            if (now - _lastDistanceSampleTime >= DISTANCE_SAMPLE_INTERVAL)
            {
                Vector3 currentPos = localPlayer.GetPosition();
                _accumulatedDistance += Vector3.Distance(currentPos, _lastPosition);
                _lastPosition = currentPos;
                _lastDistanceSampleTime = now;

                CheckMoveMilestones();
            }

            // ===== Player Count Periodic Send (every 5 minutes) =====
            if (now - _lastPcSendTime >= PC_SEND_INTERVAL)
            {
                if (_pcUrls != null && _pcUrls.Length > 0)
                {
                    int pc = Mathf.Clamp(VRCPlayerApi.GetPlayerCount(), 0, 80);
                    EnqueueSend(_pcUrls[pc]);
                }
                _lastPcSendTime = now;
            }

            // ===== Process Send Queue (5-second interval) =====
            ProcessSendQueue(now);
        }

        private void CheckStayMilestones(float elapsed)
        {
            if (_stayUrls == null || _stayUrls.Length < _stayThresholds.Length) return;

            for (int i = 0; i < _stayThresholds.Length; i++)
            {
                if (!_sentStay[i] && elapsed > _stayThresholds[i])
                {
                    EnqueueSend(_stayUrls[i]);
                    _sentStay[i] = true;
                }
            }
        }

        private void CheckMoveMilestones()
        {
            if (_moveUrls == null || _moveUrls.Length < _moveThresholds.Length) return;

            for (int i = 0; i < _moveThresholds.Length; i++)
            {
                if (!_sentMove[i] && _accumulatedDistance > _moveThresholds[i])
                {
                    EnqueueSend(_moveUrls[i]);
                    _sentMove[i] = true;
                }
            }
        }

        // ===== Platform Detection =====
        // Index: 0=PCVR, 1=Desktop, 2=Quest, 3=Android Mobile, 4=iOS

        private void SendPlatformEvent(VRCPlayerApi player)
        {
            if (_platformUrls == null || _platformUrls.Length < 5) return;

            int platformIndex;
#if UNITY_IOS
            platformIndex = 4;
#elif UNITY_ANDROID
            platformIndex = player.IsUserInVR() ? 2 : 3;
#else
            platformIndex = player.IsUserInVR() ? 0 : 1;
#endif
            EnqueueSend(_platformUrls[platformIndex]);
        }

        // ===== Ring Buffer Queue Operations =====

        private void EnqueueSend(VRCUrl url)
        {
            if (url == null) return;

            int nextTail = (_sendQueueTail + 1) % QUEUE_SIZE;
            if (nextTail == _sendQueueHead)
            {
                Debug.LogWarning("[VRClarity] Send queue full. Dropping oldest entry.");
                _sendQueueHead = (_sendQueueHead + 1) % QUEUE_SIZE;
            }

            _sendQueueUrls[_sendQueueTail] = url;
            _sendQueueTail = nextTail;
        }

        private void ProcessSendQueue(float now)
        {
            if (!_trackingActive)
            {
                // Local debug / tracking disabled: never send heartbeats. Send the
                // config-check URL once so the creator can confirm key/secret are
                // wired correctly, then discard any queued heartbeats unsent.
                if (!_verifySent && _verifyUrl != null && now - _lastRequestTime >= SEND_INTERVAL)
                {
#if UNITY_EDITOR
                    Debug.Log($"[VRClarity] Sending config-check request: {_verifyUrl}");
#endif
                    VRCStringDownloader.LoadUrl(_verifyUrl, (IUdonEventReceiver)this);
                    _verifySent = true;
                    _lastRequestTime = now;
                }
                _sendQueueHead = _sendQueueTail; // drop queued heartbeats
                return;
            }

            if (_sendQueueHead == _sendQueueTail) return; // Queue empty
            if (now - _lastRequestTime < SEND_INTERVAL) return; // Rate limit

            VRCUrl url = _sendQueueUrls[_sendQueueHead];
            _sendQueueHead = (_sendQueueHead + 1) % QUEUE_SIZE;

            if (url != null)
            {
#if UNITY_EDITOR
                Debug.Log($"[VRClarity] Sending request: {url}");
#endif
                VRCStringDownloader.LoadUrl(url, (IUdonEventReceiver)this);
                _lastRequestTime = now;
            }
        }

        // ===== Callbacks =====

        public override void OnStringLoadSuccess(IVRCStringDownload result)
        {
#if UNITY_EDITOR
            // In editor, surface the config-check response so the creator can
            // confirm the Key ID / Encryption Key are accepted by the server.
            if (!_trackingActive)
            {
                Debug.Log($"[VRClarity] Config-check response: {result.Result}");
            }
#endif
        }

        public override void OnStringLoadError(IVRCStringDownload result)
        {
            Debug.LogWarning($"[VRClarity] Send failed: {result.ErrorCode}");
        }
    }
}
